### ISSUE TITLE
Add argument "-deleteTemp" which if its specified will delete the Temporary folder if it exists and its empty

### ISSUE THREAD

**Issue by SrgjanX** [SrgjanX/SRX.ViTool#3]
Temporary folder is automatically created in ViberDownloads folder.
"~\ViberDownloads\Temporary"

**Comment by SabbirAhmedAdor629** [comment]
hi can i work on this issue

**Comment by SrgjanX** [comment]
> hi can i work on this issue

okay you are assigned to the issue,
please fork the project, create a branch, do the change and make a pull request.

**Comment by Filip235** [comment]
Let me fix this
